[platformio]
default_envs = transmitter, receiver

[env]
platform = espressif32@7.0.1
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

[env:transmitter]
build_src_filter =
    +<transmitter/>
    -<receiver/>
    -<eavesdropper/>

[env:receiver]
build_src_filter =
    -<transmitter/>
    +<receiver/>
    -<eavesdropper/>

[env:eavesdropper]
build_src_filter =
    -<transmitter/>
    -<receiver/>
    +<eavesdropper/>

